### ISSUE TITLE
Test Tutorial

### ISSUE THREAD

**Issue by ineiti** [c4dt/service-stainless#13]
Linus and Valérian need to go through the stainless tutorial to check for errors and things that are difficult to understand.
- [x] Linus
- [x] Valérian

Start with
`localstorage.clear()`
before testing.

**Comment by tharvik** [comment]
So, here goes a quick review, a bit arbitrary, discuss it with me if you don't agree
* background is default color (not white in my browser) which gives weird borders
* justifing text for big enough paragraphs might make it smoother to read
* in-text icons are aligned with superscript and not script, they might be a bit big too 
* "Tutorial" would be better in "Start" (it's weird to have an empty section)
* "Components of the demonstrator": picture are unneeded
* when verifiying, there is this unrelated line in the result `valid | cast correctness | payableAddressToAddress | stainless_smart*:142:29→142:29`
* there is no error showing when failing to execute transaction (eating more candies then there is)
* "A real-life example: the DAO": "The former one models an extrimely" -> "extremely"
* add line numbers in text viewer
* "DAO_bad.scala", maybe exchange Contracts? Start with DAO and then attack

**Comment by cgrigis** [comment]
Thank you for the feedback!

>     * background is default color (not white in my browser) which gives weird borders
>     * justifing text for big enough paragraphs might make it smoother to read
>     * in-text icons are aligned with superscript and not script, they might be a bit big too
>     * "Tutorial" would be better in "Start" (it's weird to have an empty section)
>     * "Components of the demonstrator": picture are unneeded
>     * "A real-life example: the DAO": "The former one models an extrimely" -> "extremely"
>     * add line numbers in text viewer
>     * "DAO_bad.scala", maybe exchange Contracts? Start with DAO and then attack

Thank you, will correct these.

>     * when verifiying, there is this unrelated line in the result `valid | cast correctness | payableAddressToAddress | stainless_smart*:142:29→142:29`

I am displaying the "raw" Stainless report for now, so I'd rather keep this in, as the format/contents appears to change while Stainless-Solidity evolves.

>     * there is no error showing when failing to execute transaction (eating more candies then there is)

Yes indeed. :)
Not a trivial fix, I opened dedis/cothority/issues/2074 to track the more generic issue of transaction feedback to the user.

**Comment by ineiti** [comment]
For the order of the contracts, I like to have the `DAO bad` first - this is the interesting thing. The `DAO good` is not really interesting ;)

**Comment by cgrigis** [comment]
> For the order of the contracts, I like to have the `DAO bad` first - this is the interesting thing. The `DAO good` is not really interesting ;)

Ah, I agree with that. I had understood @tharvik's remark as changing the order of contracts within the `DAO_{good,bad}` projects, i.e. having the `DAO` contract first and the `Malicious` contract after, which made sense to me and is what I changed.

**Comment by tharvik** [comment]
> > For the order of the contracts, I like to have the `DAO bad` first - this is the interesting thing. The `DAO good` is not really interesting ;)
> 
> Ah, I agree with that. I had understood @tharvik's remark as changing the order of contracts within the `DAO_{good,bad}` projects, i.e. having the `DAO` contract first and the `Malicious` contract after, which made sense to me and is what I changed.

And you understood correctly; I still find that having the `DAO_good` first flows more with the tutorial. IMO, even if the good one is not interesting, it doesn't reveal what's coming up in the tutorial, keeping the reader focused. Otherwise, the one reading it will focus on finding the bug and not understanding the system and how the tools can help.

**Comment by ineiti** [comment]
2:1 - you guys win...
