### ISSUE TITLE
Test contracts for Protean on BEvm

### ISSUE THREAD

**Issue by cgrigis** [c4dt/service-stainless#19]
Discussing with @ceyhunalp, the following EVM contracts are under consideration to be used as benchmarks for Protean:
* [Decentralized lottery](https://github.com/amiller/zero-collateral-lottery)
* [E-voting](https://github.com/stonecoldpat/anonymousvoting)

Try to run them in BEvm to ensure proper support.

**Comment by cgrigis** [comment]
Some extra information about "Decentralized lottery", for reference:
* Paper: https://arxiv.org/pdf/1612.05390.pdf
* Serpent information (language used in the contract implementation): https://github.com/ethereum/wiki/wiki/Serpent-%5BDEPRECATED%5D

**Comment by cgrigis** [comment]
Some extra information about "Decentralized lottery", for reference:
* Paper: https://arxiv.org/pdf/1612.05390.pdf
* Serpent information (language used in the contract implementation): https://github.com/ethereum/wiki/wiki/Serpent-%5BDEPRECATED%5D

**Comment by cgrigis** [comment]
Some notes after studying further the two contracts and playing with BEvm:

* Decentralized Lottery
  * Bytecode produced by the (old and no longer supported) Serpent compiler does not seem to work properly on BEvm. As the contract is fairly small, it should be easy to rewrite it in Solidity or Vyper. Quick tests were done to ensure Vyper-produced bytecode runs on BEvm.
* E-Voting
  * The code is written in "old" Solidity (v0.4.3/v0.4.10), which requires an old compiler; porting it to recent Solidity is not trivial (uses inline assembly, deprecated constructs, etc.) but doable if necessary.
  * In order to be successfully deployed on BEvm, the `AnonymousVoting` contract requires to be compiled using the `--optimize` option, to avoid running into "gas limit" issues (it's a large contract).
  * Usage of the `LocalCrypto` contract, whose purpose is to allow common code to be used by the voters and the contract, must be minimally changed to convert to view methods (should be trivial).

* Common
  * Both contracts use the `now` (or `block.numner`/`block.timestamp`) special variable, which is not yet supported by BEvm.
  * Values returned by Ethereum transactions are not visible by user-controlled accounts, which makes general usage as well as debugging awkward at best (there is no feedback). The Ethereum way is to use Events, which are not yet supported in BEvm.
  * The contract methods use various input/output types. BEvm currently supports only very few types in (de)serialization, which will need to be improved.

**Comment by ineiti** [comment]
Ping ceyhun to know if he needs advance of this issue.

**Comment by cgrigis** [comment]
The latest work on BEvm has brought some related improvements:
* `now` is now supported.
* Many more types are supported in (de)serialization, which should cover these contracts.

There is also now the possibility to call ByzCoin contracts from BEvm contracts (see dedis/cothority/pull/2220).

@ceyhunalp: do you need other improvements or tests related to your work on Protean?
