### ISSUE TITLE
Use system certificate in stainless docker

### ISSUE THREAD

**Issue by cgrigis** [c4dt/service-stainless#30]
Currently, the certificate and private key files are manually copied from `/etc/letsencrypt/live/demo.c4dt.org/` to `/home/stainless/conode_data/conode-1/`, and need to be manually updated whenever the certificate expires.
Find a way to have the docker automatically follow the system files (mount? hard link? crontab?).

**Comment by ineiti** [comment]
probably crontab, as hard-links are not available cross-device: `/home` is mounted elsewhere than `/etc/letsencrypt`...

**Comment by ineiti** [comment]
Will be taken care of by c4dt/TODO#74
