### ISSUE TITLE
Stainless examples

### ISSUE THREAD

**Issue by ineiti** [c4dt/service-stainless#7]
- [ ] Write down and chose 2 additional examples, from the existing stainless libraries, or a new one.
Ideas for smart contracts:
- Loan
- Financial product
- Insurance
- Supply chain management
- Voting ?

- [ ] Ask partners how they would want to use smart contracts
- [ ] SwissRe might want to use smart-contracts for access control management
   - [ ] have additional Darc-expression that points to Bevm+contract+view-method

**Comment by cgrigis** [comment]
Interesting contract examples in Solidity are given [here](https://solidity.readthedocs.io/en/v0.5.3/solidity-by-example.html):
* Voting
* Blind Auction
* Safe Remote Purchase
* Micropayment Channel

Porting those to Stainless would furthermore be a good exercise in defining verification conditions, and would help testing/improving the Solidity support in Stainless.

**Comment by ineiti** [comment]
Effectively looks interesting.

**Comment by ineiti** [comment]
Keep for eventual training

**Comment by ineiti** [comment]
Closing old issue
