### ISSUE TITLE
BEvm: link to BEvmID through bevm_value's DarcID

### ISSUE THREAD

**Issue by cgrigis** [c4dt/service-stainless#8]
In order to prepare the field for future work on ByzCoin sharding, it would be good to have a link from the `bevm_value` instances to the `bevm` instance that created and handles them.
For this purpose, we can "abuse" the DarcID field in the `bevm_value`; indeed, these instances will never be invoked, and therefore the DarcID will never be used.

**Comment by ineiti** [comment]
Not needed anymore
